### ISSUE TITLE
All images with the same default size

### ISSUE THREAD

**Issue by santiyounger** [BlueGreenMagick/image-style-editor#14]
Hey, thanks for making this, it is definitely the solution I was looking for. Since most of the times the images I use are way too big on my reviewer view.

---

I'm stuck trying to add a default for all images.

So far I've been able to individually right click on an image (when editing a card with an image)

and I see the original dimensions, then I need to click on "Default" in order to load my default size which right now is set to `600px`

![image](https://user-images.githubusercontent.com/51902730/118543428-dfb24600-b719-11eb-8aab-e0920bc7fc9d.png)

![image](https://user-images.githubusercontent.com/51902730/118543445-e476fa00-b719-11eb-823c-449481434a2f.png)

Here are my settings in the config

```json
{
    "empty_means": "auto",
    "hidden-div-for-image-only-field": false,
    "max-size": false,
    "min-size": false,
    "zdefaults": {
        "Apply to all fields": true,
        "Apply to all notes": true,
        "height": "",
        "max-height": "",
        "max-width": "",
        "min-height": "",
        "min-width": "",
        "width": "600px"
    },
    "zzimage-occlusion-field-position": [
        3,
        4,
        10,
        11
    ],
    "zzimage-occlusion-hidden-div": true,
    "zzimage-occlusion-id-field": "ID (hidden)",
    "zzimage-occlusion-note-type": "Image Occlusion Enhanced",
    "zzz-version-checkpoint": "2.4"
}
```

the only lines I've change are

```json
    "empty_means": "auto",
```
and 
```json
        "width": "600px"
```

What I'd like to achieve is for every image to already be set to 600px.
Without me having to right click > click default. SInce that would be a lot of manual work everytime I add or modify an image.

---

Ideally I'd want for every photo across all of my decks to be converted to have 600px.

Is this possible? Perphas it already is but I'm stuck figuring it out.

Thank you

**Comment by BlueGreenMagick** [comment]
That sounds like a useful feature to have, but it's not currently possible with this add-on.

**Comment by santiyounger** [comment]
> That sounds like a useful feature to have, but it's not currently possible with this add-on.

thanks for letting me know! That's okay, still I really enjoy this addon. Keep up the great work!
Do you perhaps know of an addon or technique than can achieve something like this? I've been stuck trying to find a solution

Thanks
