### ISSUE TITLE
ASK 

### ISSUE THREAD

**Issue by aboali19** [BlueGreenMagick/image-style-editor#16]
ImageResizer ADDon and image style editor
there are made 
to show images with wanted scale in the preview window ???  
 or
to show images with wanted scale in the Edit window only  ???

**Comment by BlueGreenMagick** [comment]
Both add-ons' goal is to show the wanted image size in the _reviewer_, but the images should also be resized in the editor and the previewer as well. (As long as the size isn't too big)

**Comment by aboali19** [comment]
@BlueGreenMagick  
Sorry, but both were not playing their target.  I tried them for now and then but I did not find any response at all.  please try to give it a shot to fix.
I am sure, Resizing images in Reviewer is the only thing that is missing in Anki.

**Comment by BlueGreenMagick** [comment]
To clarify, you are resizing the image in the **editor**, right? You can only _edit_ the image size in the editor, and the image will  _displayed_ in that size in the reviewer. If you want to resize in the reviewer, you'll want to use [this addon](https://ankiweb.net/shared/info/385888438) instead.

If you are trying and failing to resize in the editor, can you leave more details? How is the add-on not working? What version of Anki are you using? I'd also very appreciate it if you could post a screenshot.
