### ISSUE TITLE
doesn't work when a line break is in the html source

### ISSUE THREAD

**Issue by ijgnd** [BlueGreenMagick/image-style-editor#3]
First of all: Thanks for sharing this add-on and sorry for the following hasty issue. I don't use your add-on so I might have missed something?

I recently got a one sentence report that my "add table add-on" breaks "image style editor". 

I did a quick check and indeed when I add a simple table to a field there's no value for "original width" and "original height" in the "Style Editor" dialog that I open from the context menu after right clicking an image in my editor. 

It's apparently not about tables but about line breaks in the html source. This doesn't work: 
```html
<img src="qev3z18vtwp31.png">
<div>test</div>
```

This works: 
```html
<img src="qev3z18vtwp31.png"><div>test</div>
```

Debug Info:

    
    Anki 2.1.20 (47a1bf8b) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-03-03 09:37:52
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Table ['1237621971', 2019-11-06T22:23, 'None', mod]
    Image Style Editor ['1593969147', 2020-01-29T14:06, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1237621971 1593969147
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by BlueGreenMagick** [comment]
Thanks for the bug report. I believe I found the issue on my code. I'll update the addon soon

**Comment by BlueGreenMagick** [comment]
Fixed!
